version: "3.8"

services:
  react-proxy:
    container_name: proxy
    hostname: proxy
    image: nginx:alpine
    ports:
      - '8080:8080'
    volumes:
      - './docker/nginx.conf:/etc/nginx/nginx.conf'
      - './build:/build'
      - './data:/build/static-data'
    # profiles: [ microservices ]
    networks: [ "react" ]
# http://127.0.0.1:8080/static-data/collection
# http://127.0.0.1:8080
networks:
  react:
    name: react
