version: "3.8"

services:
  reverse-proxy:
    container_name: proxy
    hostname: proxy
    image: nginx:alpine
    ports:
      - '8080:8080'
    volumes:
      - './docker/nginx.conf:/etc/nginx/nginx.conf'
      - './data:/data'
    # profiles: [ microservices ]
   networks: [ "react" ]

networks:
  microservice:
    name: react
